name: create_deb_package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install python depends
        shell: bash
        run: pip install libtorrent python-telegram-bot

      - name: Build bbg-telegram-media-server
        shell: bash
        run: cd build && ./build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
