name: create_deb_package

on:
  push:
    tags:
      - 'v*'

jobs:
  create_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          platforms: linux/arm/v7
          tags: armv7:latest

  build_and_release:
    needs: create_docker_image
    runs-on: ubuntu-latest
    container:
      image: armv7:latest
    
    steps:

      - name: Build bbg-telegram-media-server
        shell: bash
        run: cd build && ./build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
